name: Update packages

on:
  schedule:
    - cron:  '0 0 * * 0'
  workflow_dispatch:
  pull_request:

jobs:
  update:
    runs-on: windows-latest

    name: Update dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Current .NET SDK
        uses: actions/setup-dotnet@v1.7.2

      - name: Run Nukeeper
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          dotnet tool install nukeeper --global
          nukeeper repo https://github.com/KuraiAndras/SharpBoard.git $env:GITHUB_TOKEN -a 0