name: Run CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  RunCI:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Setup Current .NET SDK
        uses: actions/setup-dotnet@v1.7.2

      - name: Setup Tools .NET SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.x'

      - name: Run CI
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        run: ./build.ps1 RunCi --configuration Release
